---
title: "Tarea #2 Graficación y Tidyverse"
output: html_document
---
```{r dplye}
# dplyr
library(dplyr)
```

```{r}
# Carga de graphics
library(graphics)
```

```{r}
# Carga de ggplot2
library(ggplot2)
```

```{r}
# Carga de plotly
library(plotly)
```


```{r}
# Carga de tidyverse
library(tidyverse)
```

```{r}
# Carga de hrbrthemes
library(hrbrthemes)
```

```{r}
# Carga de sqldf
```

```{r}
# carga de tid 
```


## 1. Gráfico de barras apiladas que muestre el caudal de los ríos Pandora y Bananito por cada uno de los 12 meses del año.

```{r}
# Carga de datos desde un archivo CSV
rios <-   
  read.csv(file = 'https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/hidrologia/fdc/fdc.csv')
```


```{r} 
# Cambio de nombre de las columnas mediante rename()
rios <-  
  rios %>%
  rename(fecha = Tiempo,  
         pandora = Pandora.mm..637km2.,
         banano = Banano.mm..90km2.)%>%
  mutate (fecha = as.Date(fecha, format = "%m/%d/%Y"),
         promedio = (pandora + banano) / 2)
```



```{r pandora}
# Selección, renombramiento, filtrado y conversión de columnas
rios_sumarizado_x_mes <-
  rios %>%
  select(fecha, pandora, banano) %>%
  rename(fecha = fecha, caudal_pandora = pandora, caudal_banano = banano) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by( mes = format(fecha,"%m")) %>%
  summarise(suma_caudal_pandora = sum(caudal_pandora), suma_caudal_banano = sum(caudal_banano))

# Despliegue del data frame con los resultados
rios_sumarizado_x_mes
```

```{r}
# Grafico de barras apiladas
ggplot(
  rios_sumarizado_x_mes,
  aes(x = mes, y= (suma_caudal_pandora) , (suma_caudal_banano)), fill= color) +
  geom_col(position = "dodge") +
  coord_flip() +
  ggtitle( "Caudal total por mes de los río Pandora y Banano, Limón, Costa Rica") +
  xlab("Mes") +
  ylab("Caudal") +
  theme_gray(base_size = 12)
```



## 2 Realizar un histograma que muestre la distribución de los casos nuevos de covid en Costa Rica.

```{r}
# Carga de datos desde un archivo CSV
covid <- 
  read.csv(
    file='https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/minsalud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )
```

```{r histograma}
covid_ <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))
```
  
```{r histograma_}
# Histograma Casos nuevos de COVID-19
ggplot(covid_, aes(x = fecha, y = positivos_nuevos)) +
  geom_histogram(binwidth = 5, stat= 'identity', color= "light blue" ) +
  ggtitle("Distribución de casos nuevos de Covid-19 en Costa Rica") +
  xlab("Fecha")+
  ylab("Total de casos")+
  theme_ipsum()
```

## 3 Gráfico de barras agrupadas que muestre la cantidad de hombres y mujeres fallecidos por covid en Costa Rica por cada uno de los 12 meses del año.

```{r covid}
# Carga de datos desde un archivo CSV
covid <- 
  read.csv(
    file='https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/minsalud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )
```

```{r cambio-columnas} 
# Cambio de nombre de las columnas mediante rename()
covid <-  
  covid %>%
  select(FECHA, muj_fall, hom_fall) %>%
  rename(
    fecha = FECHA,  
    mujeres_fallecidas = muj_fall,
    hombres_fallecidos = hom_fall)%>%
  mutate (fecha = as.Date(fecha, format = "%m/%d/%Y"),
         promedio = (mujeres_fallecidas + hombres_fallecidos) / 2)
```

```{r covid-seleccion}
# Selección, renombramiento, filtrado y conversión de columnas
covid_sumarizado_x_mes <-
  covid %>%
  select(fecha, mujeres_fallecidas, hombres_fallecidos) %>%
  rename(fecha = fecha, mujeres = mujeres_fallecidas, hombres = hombres_fallecidos) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by( mes = format(fecha,"%m")) %>%
  summarise(suma_mujeres_fallecidas = sum(mujeres), suma_hombres_fallecidos = sum(hombres))

# Despliegue del data frame con los resultados
covid_sumarizado_x_mes
```

```{r grafico-agrupadas}
# Grafico de barras agrupadas
ggplot(
  covid_sumarizado_x_mes,
  aes(x = mes, y= (suma_mujeres_fallecidas) , (suma_hombres_fallecidos))) +
  geom_col(position= "dodge") +
  ggtitle( "Total mujeres y hombres fallecidos") +
  xlab("Mes") +
  ylab("Fallecimientos") +
  theme_light()
```


